[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contract = "CbKtS5cKQLBKS9Hn89jpxoRLQvG9KdjcqsaHhdZqaVwx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/averek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
